name: build and tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: javascript/yarn.lock
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: ".java-version"
          distribution: "temurin"
          cache: "gradle"
      - name: Run postgres
        run: docker-compose up -d
      - name: build frontend
        run: |
          cd javascript
          yarn install
          yarn run build
      - name: Run build and tests
        run: ./gradlew test